### ISSUE TITLE
Notifications.Wpf.Core and Windows Server 2019

### ISSUE THREAD

**Issue by netfixdevo** [mjuen/Notifications.Wpf.Core#4] opened 2023-02-02 10:16 UTC
Is there any reason why a toast wouldn't show when launched from a .NET6 WPF app on Windows Server 2019 ?

Trying something as simple as this...works perfectly fine when running the WPF app on W8, W10 and W11

    var _notificationManager = new NotificationManager(NotificationPosition.BottomRight);

          var content = new CustomThemedNotificationContent
          {
              Title = title,
              Message = message,
              Type = notificationType
          };

          await _notificationManager.ShowAsync(content);

Thanks

**Comment by mjuen** [comment] 2023-02-02 23:34
I am currently unable to reproduce the problem. 

![image](https://user-images.githubusercontent.com/7404431/216474752-ccfa9831-f093-44eb-b7e0-4be316a96487.png)

I tested the sample application on Windows Server 2019 (V1809) and it did work fine. You can see a picture above, which shows all available notifications, including the custom one.

Could you please verify if the sample application works on the affected server?

**Comment by mjuen** [comment] 2023-04-21 13:10
Closing this issue as it seems to be solved since no reply has been posted in more than 2 months.

**Closed as completed by mjuen** 2023-04-21 13:10 UTC
